services:
  - type: web
    name: sellphones-backend
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: REDIS_HOST
        fromService:
          type: redis
          name: sellphones-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: sellphones-redis
          property: port
      - key: REDIS_PASSWORD
        fromService:
          type: redis
          name: sellphones-redis
          property: password

  - type: redis
    name: sellphones-redis
    plan: free
    region: oregon
