spring:
  jwt:
    secret: ${JWT_SECRET}
    access-expiration: ${JWT_ACCESS_EXPIRATION:900000}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:1209600000}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD:}
    ssl: true

  mail:
    host: "smtp.gmail.com"
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}
  backend:
    url: ${APP_BASE_URL:http://localhost:8080}
  payment:
    vnpay:
      hashSecret: ${VNPAY_HASH_SECRET}
      url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
      command: "pay"
      currCode: "VND"
      locale: "vn"
      orderInfo: "Thanh toan don hang"
      orderType: 110000
      returnUrl: ${VNPAY_RETURN_URL}
      tmnCode: ${VNPAY_TMN_CODE}
      version: "2.1.0"
      successRedirectUrl: ${VNPAY_SUCCESS_REDIRECT_URL}
      failRedirectUrl: ${VNPAY_FAIL_REDIRECT_URL}

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
